[project]
name = "advent"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=5.3.0",
    "pyperclip>=1.9.0",
    "requests>=2.32.3",
]

[tool.ruff]
line-length = 120
